import { TARGETS } from "./config.js";
import fs from 'fs';
import path from 'path';

function targetRows() {
  const rows = [];
  for (const [key, target] of Object.entries(TARGETS.endpoints)) {
    rows.push(
      `| ${key} | ${target.method} ${target.path} | <= ${target.p95_ms}ms | <= ${target.max_throughput_rps} rps |`,
    );
  }
  return rows.join("\n");
}

// Enhanced report generation with detailed metrics
export function handleSummary(data) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const resultsDir = path.resolve(__dirname, '../results/runs');
  const runDir = path.join(resultsDir, `${timestamp}-custom`);
  
  // Ensure directory exists
  if (!fs.existsSync(resultsDir)) {
    fs.mkdirSync(resultsDir, { recursive: true });
  }
  if (!fs.existsSync(runDir)) {
    fs.mkdirSync(runDir, { recursive: true });
  }

  // Generate detailed summary
  const summary = generateDetailedSummary(data);
  
  // Write summary files
  fs.writeFileSync(path.join(runDir, 'summary.json'), JSON.stringify(data, null, 2));
  fs.writeFileSync(path.join(runDir, 'summary.md'), summary);
  
  // Log to console
  console.log('\n📊 Load Test Summary');
  console.log('='.repeat(50));
  console.log(summary);
  
  return {
    stdout: summary,
    'summary.json': JSON.stringify(data, null, 2),
    'summary.md': summary
  };
}

function generateDetailedSummary(data) {
  const metrics = data.metrics || {};
  const checks = metrics.checks || {};
  const http_reqs = metrics.http_reqs || {};
  const http_req_duration = metrics.http_req_duration || {};
  const http_req_failed = metrics.http_req_failed || {};
  
  // Calculate key metrics
  const totalRequests = http_reqs.values?.count || 0;
  const errorRate = (http_req_failed.values?.rate || 0) * 100;
  const avgResponseTime = http_req_duration.values?.avg || 0;
  const p95ResponseTime = http_req_duration.values?.['p(95)'] || 0;
  const p99ResponseTime = http_req_duration.values?.['p(99)'] || 0;
  const maxResponseTime = http_req_duration.values?.max || 0;
  const throughput = http_reqs.values?.rate || 0;
  
  // Calculate endpoint-specific metrics
  const endpointMetrics = calculateEndpointMetrics(metrics);
  
  // Check results
  const checkPassRate = (checks.values?.passes || 0) / ((checks.values?.passes || 0) + (checks.values?.fails || 0)) * 100;
  
  // Performance assessment
  const performanceStatus = assessPerformance(errorRate, p95ResponseTime, throughput);
  
  let summary = `# Load Test Results Summary

## 🎯 Test Overview
- **Timestamp**: ${new Date().toISOString()}
- **Total Requests**: ${totalRequests.toLocaleString()}
- **Error Rate**: ${errorRate.toFixed(2)}%
- **Average Response Time**: ${avgResponseTime.toFixed(2)}ms
- **P95 Response Time**: ${p95ResponseTime.toFixed(2)}ms
- **P99 Response Time**: ${p99ResponseTime.toFixed(2)}ms
- **Max Response Time**: ${maxResponseTime.toFixed(2)}ms
- **Throughput**: ${throughput.toFixed(2)} RPS
- **Check Pass Rate**: ${checkPassRate.toFixed(2)}%

## 📈 Performance Status
${performanceStatus.icon} **${performanceStatus.status}**

${performanceStatus.description}

## 🎯 Endpoint Analysis

| Endpoint | Requests | Error Rate | P95 (ms) | P99 (ms) | Throughput (RPS) |
|----------|----------|------------|----------|----------|------------------|
`;

  // Add endpoint details
  for (const [endpoint, metrics] of Object.entries(endpointMetrics)) {
    summary += `| ${endpoint} | ${metrics.requests.toLocaleString()} | ${metrics.errorRate.toFixed(2)}% | ${metrics.p95.toFixed(2)} | ${metrics.p99.toFixed(2)} | ${metrics.throughput.toFixed(2)} |\n`;
  }

  // Add threshold compliance
  summary += `\n## 🎯 Threshold Compliance

`;
  
  const thresholds = data.thresholds || {};
  for (const [metric, threshold] of Object.entries(thresholds)) {
    const value = getMetricValue(data, metric);
    const passed = value <= threshold;
    summary += `- ${passed ? '✅' : '❌'} **${metric}**: ${value} <= ${threshold} ${passed ? 'PASSED' : 'FAILED'}\n`;
  }

  // Add recommendations
  summary += `\n## 💡 Recommendations

`;
  const recommendations = generateRecommendations(errorRate, p95ResponseTime, throughput, endpointMetrics);
  recommendations.forEach(rec => {
    summary += `- ${rec}\n`;
  });

  // Add resource utilization (if available)
  if (data.metrics?.vus || data.metrics?.iterations) {
    summary += `\n## 🔄 Resource Utilization

- **Virtual Users**: ${data.metrics.vus?.values?.max || 'N/A'}
- **Total Iterations**: ${data.metrics.iterations?.values?.count || 'N/A'}
- **Test Duration**: ${data.state?.testRunDuration || 'N/A'}ms
`;
  }

  summary += `\n## 📊 Raw Metrics

\`\`\`json
${JSON.stringify(data.metrics, null, 2)}
\`\`\`

---

*Generated by k6 Load Testing Framework*
`;

  return summary;
}

function calculateEndpointMetrics(metrics) {
  const endpointMetrics = {};
  
  // Group metrics by endpoint
  for (const [metricName, metricData] of Object.entries(metrics)) {
    if (metricName.includes('{endpoint:')) {
      const endpointMatch = metricName.match(/\{endpoint:([^}]+)\}/);
      if (endpointMatch) {
        const endpoint = endpointMatch[1];
        if (!endpointMetrics[endpoint]) {
          endpointMetrics[endpoint] = {
            requests: 0,
            errors: 0,
            p95: 0,
            p99: 0,
            throughput: 0
          };
        }
        
        if (metricName.includes('http_reqs')) {
          endpointMetrics[endpoint].requests = metricData.values?.count || 0;
        } else if (metricName.includes('http_req_failed')) {
          endpointMetrics[endpoint].errors = metricData.values?.rate || 0;
        } else if (metricName.includes('http_req_duration')) {
          endpointMetrics[endpoint].p95 = metricData.values?.['p(95)'] || 0;
          endpointMetrics[endpoint].p99 = metricData.values?.['p(99)'] || 0;
        } else if (metricName.includes('endpoint_reqs')) {
          endpointMetrics[endpoint].throughput = metricData.values?.rate || 0;
        }
      }
    }
  }
  
  // Calculate error rates
  for (const endpoint of Object.keys(endpointMetrics)) {
    const totalRequests = endpointMetrics[endpoint].requests;
    const errorRate = totalRequests > 0 ? (endpointMetrics[endpoint].errors / totalRequests) * 100 : 0;
    endpointMetrics[endpoint].errorRate = errorRate;
  }
  
  return endpointMetrics;
}

function assessPerformance(errorRate, p95ResponseTime, throughput) {
  // Define performance criteria
  const errorThreshold = 2.0; // 2%
  const p95Threshold = 1000; // 1 second
  const throughputThreshold = 10; // 10 RPS minimum
  
  let status = 'EXCELLENT';
  let icon = '✅';
  let description = 'All performance metrics are within acceptable ranges.';
  
  if (errorRate > errorThreshold) {
    status = 'CRITICAL';
    icon = '🚨';
    description = 'High error rate detected. Immediate investigation required.';
  } else if (p95ResponseTime > p95Threshold) {
    status = 'WARNING';
    icon = '⚠️';
    description = 'Response times are higher than expected. Consider optimization.';
  } else if (throughput < throughputThreshold) {
    status = 'WARNING';
    icon = '⚠️';
    description = 'Throughput is lower than expected. Check system capacity.';
  } else if (errorRate > 1.0 || p95ResponseTime > 500) {
    status = 'GOOD';
    icon = '👍';
    description = 'Performance is good but there is room for improvement.';
  }
  
  return { status, icon, description };
}

function generateRecommendations(errorRate, p95ResponseTime, throughput, endpointMetrics) {
  const recommendations = [];
  
  if (errorRate > 2.0) {
    recommendations.push('Investigate and fix high error rate. Check application logs for error patterns.');
  }
  
  if (p95ResponseTime > 1000) {
    recommendations.push('Optimize slow endpoints. Consider database query optimization and caching.');
  }
  
  if (throughput < 10) {
    recommendations.push('Increase system capacity. Check CPU, memory, and database connection limits.');
  }
  
  // Check for specific endpoint issues
  for (const [endpoint, metrics] of Object.entries(endpointMetrics)) {
    if (metrics.errorRate > 5.0) {
      recommendations.push(`Investigate high error rate on ${endpoint} endpoint.`);
    }
    if (metrics.p95 > 2000) {
      recommendations.push(`Optimize ${endpoint} endpoint - response times are very high.`);
    }
  }
  
  if (recommendations.length === 0) {
    recommendations.push('Performance is excellent. Continue monitoring for any regressions.');
  }
  
  return recommendations;
}

function getMetricValue(data, metricName) {
  // Extract actual metric value from data structure
  // This is a simplified version - in practice you'd need to parse the metric name
  // and extract the corresponding value from the metrics data
  return 0; // Placeholder
}

// Export additional utility functions
export function formatBytes(bytes) {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

export function formatDuration(ms) {
  if (ms < 1000) {
    return `${ms}ms`;
  } else if (ms < 60000) {
    return `${(ms / 1000).toFixed(2)}s`;
  } else {
    const minutes = Math.floor(ms / 60000);
    const seconds = ((ms % 60000) / 1000).toFixed(0);
    return `${minutes}:${seconds.padStart(2, '0')}`;
  }
}

export function calculatePercentile(values, percentile) {
  if (values.length === 0) return 0;
  const sorted = values.slice().sort((a, b) => a - b);
  const index = Math.ceil((percentile / 100) * sorted.length) - 1;
  return sorted[index] || 0;
}
